import { Inter } from "next/font/google";
import "./globals.css";
import LayoutContextProvider from "../contexts/layoutContext";
import DarkModeProvider from "../components/DarkModeProvider";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "This is an test title header",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutContextProvider>
          <Header />
          <DarkModeProvider>{children}</DarkModeProvider>
        </LayoutContextProvider>
      </body>
    </html>
  );
}
